swagger: "2.0"
info:
  description: "SRE Test Loadsmart"
  version: "1.0.0"
  title: "Site Reliability Engineer Test"
contact:
  email: "jobs@loadsmart.com"
paths:
  /healthcheck!:
    get:
      description: API health check
      responses:
        200:
          description: "the service is up"